apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: ztaylor510/multi-client
          #resources:
          #  limits:
          #    memory: "128Mi"
          #    cpu: "500m"
          ports:
            - containerPort: 3000
